name: Generate Contribution Snake

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight
  workflow_dispatch:  # Allows manual execution

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Contribution Snake
        uses: Platane/snk@v3
        with:
          github_user_name: robindarkblack1
          outputs: |
            github-contribution-grid-snake.svg
            github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Push Contribution Snake to Output Branch
        run: |
          mkdir -p output
          mv github-contribution-grid-snake.svg output/
          mv github-contribution-grid-snake-dark.svg output/
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add output/
          git commit -m "Updated contribution snake"
          git push origin main
